### PR TITLE
add support for "Upload from Server"

### PR DESCRIPTION
**Pull request by alpianon**
solve #49

### CODE REVIEW

**Comment by deveaud-m** [comment]
Thanks for the PR. I was not aware of this option. Code looks good.

Could you please write a test-case for this option?

**Comment by alpianon** [comment]
the only problem is that a test-case for this option would require that the source package dir (which canno not be a tar file but should be a directory) to be uploaded is saved within the running fossology container used for tests. I cannot figure out a clean way to do that, any ideas?

**Comment by alpianon** [comment]
more precisely, the source dir to be uploaded should be put within `/tmp` in the fossology container

**Comment by deveaud-m** [comment]
> more precisely, the source dir to be uploaded should be put within `/tmp` in the fossology container

You can use the Python module tempfile to create a temporary directory in the test routine: https://docs.python.org/3/library/tempfile.html

**Comment by deveaud-m** [comment]
> But you'll also need to mount that directory into the container...

I've never done that but it seems to be possible using the keyword `volumes`: https://github.github.io/actions-cheat-sheet/actions-cheat-sheet.html

**Comment by alpianon** [comment]
so are CI tests run *within* a fossology container, by calling the fossology server running on the same container?

**Comment by deveaud-m** [comment]
> so are CI tests run _within_ a fossology container, by calling the fossology server running on the same container?

Not exactly, the tests run in a "linux" container (`python:3.9-slim`) and fossology is started as a service container on the same host instance. So both containers should be able to use the shared volume. See also: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idservicesservice_idvolumes.

You'll probably need to test this locally first to understand the volume mechanism between both containers. Porting this to the Github actions should be straight forward.

**Comment by deveaud-m** [comment]
I just tested the patch locally, it looks good to me.

I'll provide a test-case in another PR.

Thanks for the fix @alpianon!

**Pull request merged**
